(() => {'use strict';
const P=['Ruimte herkennen / vrijlopen','1v1 oplossen / man uitschakelen','Vrije speler vinden / vrijspelen','Aannemen / balcontrole','Kijken vóór spelen','Passing / inspelen','Omschakelen'];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],id=()=>crypto.randomUUID();let db;
const req=r=>new Promise((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});
function status(ok,msg){$('#storageHealth').className='health '+(ok?'ok':'error');$('#storageHealth').textContent=msg;$('#storageTitle').textContent=ok?'Opslag werkt':'Opslag niet beschikbaar';$('#storageText').textContent=ok?'Elke wijziging is in IndexedDB bewaard én teruggelezen.':msg}
async function open(){let r=indexedDB.open('kvc-u9-coach',1);r.onupgradeneeded=()=>{let d=r.result;d.createObjectStore('trainings',{keyPath:'id'});let f=d.createObjectStore('feedback',{keyPath:'id'});f.createIndex('trainingId','trainingId')};return req(r)}
async function all(s){return req(db.transaction(s).objectStore(s).getAll())}async function one(s,k){return req(db.transaction(s).objectStore(s).get(k))}async function put(s,v){let t=db.transaction(s,'readwrite');t.objectStore(s).put(v);await new Promise((ok,no)=>{t.oncomplete=ok;t.onerror=()=>no(t.error)});let confirmed=await one(s,v.id);if(!confirmed)throw Error('Opslag kon niet worden bevestigd.');status(true,'Opslag in orde')}
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));const date=d=>new Intl.DateTimeFormat('nl-BE',{dateStyle:'long'}).format(new Date(d+'T12:00:00'));
function score(items){let v=Object.fromEntries(P.map(x=>[x,0]));items.forEach(x=>{x.good.forEach(p=>v[p]--);x.difficult.forEach(p=>v[p]+=3);x.repeat.forEach(p=>v[p]+=2)});let a=Object.entries(v).sort((a,b)=>b[1]-a[1])[0];return a[1]>0?a:null}function picked(g){return $$(`[data-group="${g}"] input:checked`).map(x=>x.value)}
async function refresh(){let ts=(await all('trainings')).sort((a,b)=>b.date.localeCompare(a.date)),fs=await all('feedback'),p=score(fs);$('#priorityTitle').textContent=p?p[0]:'Nog geen prioriteit';$('#priorityText').textContent=p?`Gebaseerd op opgeslagen feedback · score ${p[1]}.`:'Sla feedback op bij een training om een voorstel te krijgen.';$('#trainingList').innerHTML=ts.length?ts.map(t=>`<article class="training-item"><span class="tag">Concept</span><h3>${esc(t.title)}</h3><p>${date(t.date)} · ${esc(t.priority)}</p><p>${fs.filter(f=>f.trainingId===t.id).length} feedback-item(s)</p></article>`).join(''):'<p>Nog geen training bewaard.</p>';let form=$('#feedbackForm'),gate=$('#feedbackGate'),sel=$('#feedbackTraining');if(!ts.length){gate.textContent='Maak en bewaar eerst een training. Daarna kun je er feedback aan koppelen.';form.classList.add('hidden')}else{gate.textContent='Kies hieronder de training waarover je feedback geeft.';form.classList.remove('hidden');let old=sel.value;sel.innerHTML=ts.map(t=>`<option value="${t.id}">${date(t.date)} — ${esc(t.title)}</option>`).join('');if(ts.some(t=>t.id===old))sel.value=old}$('#historyList').innerHTML=ts.length?ts.map(t=>{let q=fs.filter(f=>f.trainingId===t.id);return `<article class="training-item"><h3>${esc(t.title)}</h3><p>${date(t.date)} · ${esc(t.priority)}</p>${q.length?`<p><strong>${q.length} feedback-item(s)</strong></p>`+q.map(f=>`<p>✓ Goed: ${esc(f.good.join(', ')||'—')}<br>! Moeilijk: ${esc(f.difficult.join(', ')||'—')}<br>↺ Terug: ${esc(f.repeat.join(', ')||'—')}</p>`).join(''):'<p>Nog geen feedback bij deze training.</p>'}</article>`}).join(''):'<p>Nog geen trainingsdossiers.</p>'}
function view(x){$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===x));$$('.view').forEach(v=>v.classList.toggle('active',v.id===x));refresh()}
async function init(){P.forEach(p=>$('#trainingPriority').insertAdjacentHTML('beforeend',`<option>${esc(p)}</option>`));['good','difficult','repeat'].forEach(g=>{$(`[data-group="${g}"]`).innerHTML=P.map(p=>`<label><input type="checkbox" value="${esc(p)}">${esc(p)}</label>`).join('')});$('#trainingForm [name=date]').value=new Date().toISOString().slice(0,10);try{if(!window.indexedDB)throw Error();db=await open();await put('trainings',{id:'healthcheck',date:'2099-01-01',title:'__healthcheck__',priority:P[0]});let tx=db.transaction('trainings','readwrite');tx.objectStore('trainings').delete('healthcheck');status(true,'Opslag in orde');await refresh()}catch(e){console.error(e);status(false,'Opslag niet beschikbaar');$$('form button,input,select').forEach(x=>x.disabled=true)}$$('.nav').forEach(x=>x.onclick=()=>view(x.dataset.view));$$('[data-go]').forEach(x=>x.onclick=()=>view(x.dataset.go));
$('#trainingForm').onsubmit=async e=>{e.preventDefault();let s=$('#trainingStatus'),f=new FormData(e.target);try{s.textContent='Bewaren…';await put('trainings',{id:id(),type:'training',date:f.get('date'),title:f.get('title').trim(),priority:f.get('priority'),notes:f.get('notes').trim(),createdAt:new Date().toISOString()});s.textContent='✓ Training bewaard en gecontroleerd.';e.target.reset();$('#trainingForm [name=date]').value=new Date().toISOString().slice(0,10);await refresh()}catch(x){s.textContent='⚠ Training kon niet bevestigd worden.';s.className='form-status error'}};
$('#feedbackForm').onsubmit=async e=>{e.preventDefault();let s=$('#feedbackStatus'),trainingId=$('#feedbackTraining').value;try{if(!await one('trainings',trainingId))throw Error('De gekozen training bestaat niet.');let f={id:id(),type:'feedback',parentType:'training',parentId:trainingId,trainingId,good:picked('good'),difficult:picked('difficult'),repeat:picked('repeat'),createdAt:new Date().toISOString()};if(!f.good.length&&!f.difficult.length&&!f.repeat.length)throw Error('Kies minstens één feedbackpunt.');s.textContent='Bewaren…';await put('feedback',f);if(!await one('feedback',f.id))throw Error('Feedback niet teruggevonden.');s.textContent='✓ Feedback opgeslagen bij de gekozen training en gecontroleerd.';$$('#feedbackForm input').forEach(x=>x.checked=false);await live();await refresh()}catch(x){s.textContent='⚠ '+x.message;s.className='form-status error'}};$('#feedbackForm').onchange=live}
async function live(){let p=score([...(await all('feedback')),{good:picked('good'),difficult:picked('difficult'),repeat:picked('repeat')}]);$('#livePriority').textContent=p?`${p[0]} (score ${p[1]})`:'nog geen leerprioriteit'}init();
})();
