(() => {'use strict';
const PRIORITY_TAXONOMY=[
 {id:'techniek',label:'Techniek',priorities:['Balgewenning / balvaardigheid','Leiden / dribbelen','Aannemen / balcontrole','Bal beschermen / in balbezit blijven','Passing / inspelen','Trappen / afwerken','1v1 oplossen / man uitschakelen','Tweevoetigheid']},
 {id:'kijken-samenspelen',label:'Kijken & samenspelen',priorities:['Kijken vóór spelen / oriëntatie','Ruimte herkennen / vrijlopen','Vrije speler vinden / vrijspelen','Bewegen na pass','Samenspelen / keuze pass of actie','Creativiteit / eigen initiatief']},
 {id:'aanvallend-positiespel',label:'Aanvallend positiespel',priorities:['Positie begrijpen','Breedte maken','Diepte maken','Infiltreren met bal','Doelkans creëren','Snel afwerken bij doelkans']},
 {id:'verdedigend',label:'Verdedigend',priorities:['Druk zetten / bal veroveren','1v1 verdedigen / duel niet verliezen','Remmend wijken','Centrum gesloten houden','Samen verdedigen / kantelen','Korte dekking','Passlijn afsluiten / onderscheppen','Schot afblokken']},
 {id:'omschakeling',label:'Omschakeling',priorities:['Omschakelen na balverlies','Omschakelen na balwinst']},
 {id:'fysiek-coordinatie',label:'Fysiek / coördinatie',priorities:['Reactie / startsnelheid','Versnellen / vertragen','Starten / stoppen','Draaien / richtingsverandering','Algemene lichaamscoördinatie','Oog-voetcoördinatie']}
];
const P=PRIORITY_TAXONOMY.flatMap(category=>category.priorities);
const LEGACY_PRIORITY_VALUES=['Kijken vóór spelen','Omschakelen'];
const KNOWN_PRIORITY_VALUES=[...P,...LEGACY_PRIORITY_VALUES];
const priorityCategory=id=>PRIORITY_TAXONOMY.find(category=>category.id===id);
const priorityOptionGroups=()=>PRIORITY_TAXONOMY.map(category=>`<optgroup label="${esc(category.label)}">${category.priorities.map(priority=>`<option value="${esc(priority)}">${esc(priority)}</option>`).join('')}</optgroup>`).join('');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],id=()=>crypto.randomUUID();let db;
const req=r=>new Promise((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});
function status(ok,msg){$('#storageHealth').className='health '+(ok?'ok':'error');$('#storageHealth').textContent=msg;$('#storageTitle').textContent=ok?'Opslag werkt':'Opslag niet beschikbaar';$('#storageText').textContent=ok?'Elke wijziging is in IndexedDB bewaard én teruggelezen.':msg}
async function open(){let r=indexedDB.open('kvc-u9-coach',1);r.onupgradeneeded=()=>{let d=r.result;d.createObjectStore('trainings',{keyPath:'id'});let f=d.createObjectStore('feedback',{keyPath:'id'});f.createIndex('trainingId','trainingId')};return req(r)}
async function all(s){return req(db.transaction(s).objectStore(s).getAll())}async function one(s,k){return req(db.transaction(s).objectStore(s).get(k))}async function put(s,v){let t=db.transaction(s,'readwrite');t.objectStore(s).put(v);await new Promise((ok,no)=>{t.oncomplete=ok;t.onerror=()=>no(t.error)});let confirmed=await one(s,v.id);if(!confirmed)throw Error('Opslag kon niet worden bevestigd.');status(true,'Opslag in orde')}
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));const date=d=>new Intl.DateTimeFormat('nl-BE',{dateStyle:'long'}).format(new Date(d+'T12:00:00'));
const createdDate=d=>new Intl.DateTimeFormat('nl-BE',{dateStyle:'long'}).format(new Date(d));
function score(items){let v=Object.fromEntries(KNOWN_PRIORITY_VALUES.map(x=>[x,0]));items.forEach(x=>{x.good.forEach(p=>v[p]--);x.difficult.forEach(p=>v[p]+=3);x.repeat.forEach(p=>v[p]+=2)});let best=Math.max(...Object.values(v));if(best<=0)return null;let leaders=P.filter(p=>v[p]===best);return[leaders.length===1?leaders[0]:`Gelijke prioriteit: ${leaders.join(' + ')}`,best]}function picked(g){return $$(`[data-group="${g}"] input:checked`).map(x=>x.value)}
const DIAGRAM_STYLES={player:{fill:'#08783d',stroke:'#fff'},keeper:{fill:'#b7e34b',stroke:'#153000'},opponent:{fill:'#b64235',stroke:'#fff'},neutral:{fill:'#1688a8',stroke:'#fff'},ball:{fill:'#fff',stroke:'#16221d'},largeGoal:{fill:'#fff',stroke:'#16221d'},smallGoal:{fill:'#fff',stroke:'#16221d'},cone:{fill:'#f0a52b',stroke:'#814f00'},zone:{fill:'rgba(183,227,75,.16)',stroke:'#b7e34b'},passLine:{stroke:'#08783d',dash:'7 5'},runLine:{stroke:'#b7e34b',dash:'2 6'},dribbleLine:{stroke:'#1688a8',dash:'9 4 2 4'},shotLine:{stroke:'#b64235',dash:'10 4'},crossLine:{stroke:'#f0a52b',dash:'6 4'}};
const EXERCISES=[
 {id:'passing-technical-u9',title:'Technische passingvorm',source:'KVC oefenfundering',sourceType:'intern-referentie',primaryObjective:'Passing en aannemen',secondaryObjectives:['Kijken voor het spelen','Vrije speler vinden'],ageGroups:['U9'],playersMin:8,playersMax:8,idealPlayers:8,minPlayers:8,maxPlayers:8,expandable:false,expandableWithNeutralPlayers:false,rotationPossible:true,substitutePossible:true,parallelGroupPossible:true,physicalLoad:'Laag',loadProfile:{explicitSource:{physical:{field:'physicalLoad',value:'Laag'}},derivedKvcEstimate:{technical:'Hoog',tactical:'Laag'}},trainerRequirement:{minimum:null,ideal:null,source:'Niet gespecificeerd in bestaande oefengegevens'},abSuitability:{progressionAAvailable:true,progressionBAvailable:true},feedbackPriorities:['Passing / inspelen','Kijken vóór spelen','Vrije speler vinden / vrijspelen'],organizationNotes:'Twee gelijktijdige balcirculaties in één ruitvorm; spelers volgen hun pass.',scalabilityStatus:'DIRECT',durationMin:12,exerciseType:'Techniekvorm',fieldSize:'20 x 25 m',materials:['2 ballen','6 kegels'],difficulty:'Basis',organization:'Acht spelers vormen een ruit met een binnenste aanspeelpunt; zes kegels markeren de buitenposities.',coachingPoints:['Open lichaam voor ontvangst','Kijk voor het eerste balcontact','Speel strak naar de verste voet'],kvcPrinciples:['Kijken voor spelen','Passing / inspelen'],matchTransfer:'Snel herkennen van de vrije speler.',progressionA:'Een keer raken na een actieve loopactie.',progressionB:'Twee balcirculaties tegelijk laten lopen.',regression:'Afstand verkleinen en vrij aannemen.',progression:'Wissel door na elke pass.',adaptableFields:['players','durationMin','fieldSize'],diagram:{field:{width:100,height:60},goals:[],players:[{id:'p1',x:20,y:20,team:'A'},{id:'p2',x:50,y:10,team:'A'},{id:'p3',x:80,y:20,team:'A'},{id:'p4',x:80,y:45,team:'A'},{id:'p5',x:50,y:52,team:'A'},{id:'p6',x:20,y:45,team:'A'},{id:'p7',x:50,y:30,team:'A'},{id:'p8',x:35,y:35,team:'A'}],keepers:[],opponents:[],neutralPlayers:[],balls:[{id:'b1',x:20,y:20},{id:'b2',x:80,y:45}],cones:[{x:20,y:20},{x:50,y:10},{x:80,y:20},{x:80,y:45},{x:50,y:52},{x:20,y:45}],markers:[],zones:[],labels:[{text:'Pass en volg',x:50,y:6}],movements:[{type:'pass',from:{x:20,y:20},to:{x:50,y:10}},{type:'run',from:{x:20,y:20},to:{x:35,y:35}},{type:'pass',from:{x:80,y:45},to:{x:50,y:52}},{type:'run',from:{x:80,y:45},to:{x:65,y:35}}]}},
 {id:'2v2-u9',title:'2v2 met omschakeling',source:'KVC oefenfundering',sourceType:'intern-referentie',primaryObjective:'1v1 oplossen / man uitschakelen',secondaryObjectives:['Omschakelen','Ruimte herkennen / vrijlopen'],ageGroups:['U9'],playersMin:4,playersMax:4,idealPlayers:4,minPlayers:4,maxPlayers:4,expandable:true,expandableWithNeutralPlayers:false,rotationPossible:true,substitutePossible:true,parallelGroupPossible:true,physicalLoad:'Hoog',loadProfile:{explicitSource:{physical:{field:'physicalLoad',value:'Hoog'}},derivedKvcEstimate:{technical:'Gemiddeld',tactical:'Hoog'}},trainerRequirement:{minimum:null,ideal:null,source:'Niet gespecificeerd in bestaande oefengegevens'},abSuitability:{progressionAAvailable:true,progressionBAvailable:true},feedbackPriorities:['1v1 oplossen / man uitschakelen','Omschakelen','Ruimte herkennen / vrijlopen'],organizationNotes:'Vier spelers starten 2v2. Bij balwinst gaat het team direct richting het andere doel; extra spelers roteren na een intensieve beurt.',scalabilityStatus:'ORGANIZATION_ADJUSTMENT',durationMin:15,exerciseType:'Spelvorm',fieldSize:'18 x 25 m',materials:['2 kleine doelen','4 kegels','1 bal'],difficulty:'Gemiddeld',organization:'Twee aanvallers spelen tegen twee verdedigers. Balbezit leidt tot balverlies of balwinst, waarna de nieuwe aanval onmiddellijk naar het andere doel gaat.',coachingPoints:['Eerste actie vooruit','Maak de ruimte breed','Reageer direct na balverlies'],kvcPrinciples:['1v1 oplossen / man uitschakelen','Omschakelen'],matchTransfer:'Herkenbaar duelgedrag in kleine aantallen.',progressionA:'Voeg alleen een neutrale kaatser toe als extra aanspeelpunt nodig is.',progressionB:'Beperk de balbezittende ploeg tot drie contacten.',regression:'Laat verdedigers starten op halve snelheid.',progression:'Na balwinst direct naar het andere doel.',adaptableFields:['players','durationMin','fieldSize'],diagram:{field:{width:100,height:60},goals:[{type:'small',x:2,y:24,w:4,h:12},{type:'small',x:94,y:24,w:4,h:12}],players:[{id:'a1',x:25,y:22,team:'A'},{id:'a2',x:25,y:38,team:'A'},{id:'d1',x:75,y:22,team:'B'},{id:'d2',x:75,y:38,team:'B'}],keepers:[],opponents:['d1','d2'],neutralPlayers:[],balls:[{id:'b1',x:50,y:30}],cones:[{x:15,y:15},{x:15,y:45},{x:85,y:15},{x:85,y:45}],markers:[],zones:[],labels:[{text:'2v2 omschakeling',x:50,y:6}],movements:[{type:'dribble',from:{x:25,y:22},to:{x:48,y:18}},{type:'run',from:{x:25,y:38},to:{x:48,y:42}},{type:'shot',from:{x:48,y:18},to:{x:96,y:30}},{type:'ballPath',from:{x:96,y:30},to:{x:4,y:30}}]}},
 {id:'game-5v5-u9',title:'Wedstrijdvorm 5v5',source:'KVC oefenfundering',sourceType:'intern-referentie',primaryObjective:'Vrije speler vinden / vrijspelen',secondaryObjectives:['Omschakelen','Ruimte herkennen / vrijlopen'],ageGroups:['U9'],playersMin:10,playersMax:10,idealPlayers:10,minPlayers:10,maxPlayers:10,expandable:false,expandableWithNeutralPlayers:false,rotationPossible:true,substitutePossible:true,parallelGroupPossible:true,physicalLoad:'Hoog',loadProfile:{explicitSource:{physical:{field:'physicalLoad',value:'Hoog'}},derivedKvcEstimate:{technical:'Gemiddeld',tactical:'Hoog'}},trainerRequirement:{minimum:null,ideal:null,source:'Niet gespecificeerd in bestaande oefengegevens'},abSuitability:{progressionAAvailable:true,progressionBAvailable:true},feedbackPriorities:['Vrije speler vinden / vrijspelen','Omschakelen','Ruimte herkennen / vrijlopen'],organizationNotes:'Exact twee teams van vijf: één keeper en vier veldspelers per team. Extra spelers kunnen per rotatie of in een parallelle vorm deelnemen.',scalabilityStatus:'GROUP_OR_ROTATION',durationMin:20,exerciseType:'Wedstrijdvorm',fieldSize:'30 x 40 m',materials:['2 grote doelen','6 kegels','1 bal'],difficulty:'Toegepast',organization:'Keeper plus vier veldspelers tegen keeper plus vier veldspelers.',coachingPoints:['Maak het veld groot bij balbezit','Kijk voor de pass vooruit','Schakel samen om'],kvcPrinciples:['Vrije speler vinden / vrijspelen','Omschakelen'],matchTransfer:'Volledige spelcontext met twee teams van vijf.',progressionA:'Scoren telt dubbel na een pass door een vrije speler.',progressionB:'Start elke herneming bij de keeper.',regression:'Speel zonder de centrale zone als extra beperking.',progression:'Laat de coach de herneming bij de keeper variëren.',adaptableFields:['players','durationMin','fieldSize'],diagram:{field:{width:100,height:60},goals:[{type:'large',x:0,y:23,w:5,h:14},{type:'large',x:95,y:23,w:5,h:14}],players:[{id:'ak',x:8,y:30,team:'A',role:'keeper'},{id:'a1',x:25,y:15,team:'A'},{id:'a2',x:30,y:30,team:'A'},{id:'a3',x:25,y:45,team:'A'},{id:'a4',x:43,y:30,team:'A'},{id:'bk',x:92,y:30,team:'B',role:'keeper'},{id:'b1',x:75,y:15,team:'B'},{id:'b2',x:70,y:30,team:'B'},{id:'b3',x:75,y:45,team:'B'},{id:'b4',x:57,y:30,team:'B'}],keepers:['ak','bk'],opponents:['b1','b2','b3','b4','bk'],neutralPlayers:[],balls:[{id:'b1',x:43,y:30}],cones:[{x:15,y:8},{x:15,y:52},{x:85,y:8},{x:85,y:52},{x:50,y:8},{x:50,y:52}],markers:[],zones:[],labels:[{text:'5v5',x:50,y:6},{text:'Keeper + 4',x:18,y:57},{text:'Keeper + 4',x:82,y:57}],movements:[{type:'pass',from:{x:43,y:30},to:{x:30,y:30}},{type:'run',from:{x:25,y:15},to:{x:43,y:18}},{type:'cross',from:{x:30,y:30},to:{x:75,y:15}},{type:'shot',from:{x:43,y:30},to:{x:95,y:30}}]}}
];
function getScalabilityStatus(exercise,availablePlayers){
 if(availablePlayers===exercise.idealPlayers)return 'DIRECT';
 if(availablePlayers>=exercise.minPlayers&&availablePlayers<=exercise.maxPlayers)return 'DIRECT';
 if(availablePlayers<exercise.minPlayers)return 'NOT_SUITABLE';
 if(exercise.parallelGroupPossible)return 'GROUP_OR_ROTATION';
 if(exercise.expandable||exercise.expandableWithNeutralPlayers||exercise.rotationPossible||exercise.substitutePossible)return 'ORGANIZATION_ADJUSTMENT';
 return 'NOT_SUITABLE';
}
function scalabilityLabel(exercise){return exercise.parallelGroupPossible?'Flexibel inzetbaar':exercise.expandable||exercise.rotationPossible?'Geschikt met rotatie':'Direct inzetbaar'}
function diagramMarker(type,prefix){return type==='run'?`url(#${prefix}-arrow-lime)`:type==='dribble'?`url(#${prefix}-arrow-blue)`:type==='shot'?`url(#${prefix}-arrow-red)`:type==='cross'?`url(#${prefix}-arrow-orange)`:`url(#${prefix}-arrow-green)`}
function renderDiagram(exercise){let d=exercise.diagram,w=d.field.width,h=d.field.height,prefix=exercise.id,keepers=new Set(d.keepers),opponents=new Set(d.opponents),neutral=new Set(d.neutralPlayers);let svg=`<svg class="exercise-diagram" viewBox="0 0 ${w} ${h}" role="img" aria-label="Diagram van ${esc(exercise.title)}"><defs>${['green','lime','blue','red','orange'].map(c=>`<marker id="${prefix}-arrow-${c}" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="3" markerHeight="3" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="var(--diagram-${c})"/></marker>`).join('')}</defs><rect class="diagram-field" x="0" y="0" width="${w}" height="${h}"/>`;svg+=d.zones.map(z=>`<rect class="diagram-zone" x="${z.x}" y="${z.y}" width="${z.w}" height="${z.h}"/>`).join('');svg+=d.goals.map(g=>`<rect class="diagram-goal goal-${g.type||'large'}" x="${g.x}" y="${g.y}" width="${g.w}" height="${g.h}"/>`).join('');svg+=d.movements.map(m=>`<line class="diagram-movement movement-${m.type}" x1="${m.from.x}" y1="${m.from.y}" x2="${m.to.x}" y2="${m.to.y}" marker-end="${diagramMarker(m.type,prefix)}"/>`).join('');svg+=d.cones.map(c=>`<circle class="diagram-cone" cx="${c.x}" cy="${c.y}" r="1.7"/>`).join('');svg+=d.markers.map(c=>`<circle class="diagram-marker" cx="${c.x}" cy="${c.y}" r="1.5"/>`).join('');svg+=d.balls.map(b=>`<circle class="diagram-ball" cx="${b.x}" cy="${b.y}" r="1.8"/>`).join('');svg+=d.players.map(p=>{let cls=keepers.has(p.id)?'diagram-keeper':opponents.has(p.id)?'diagram-opponent':neutral.has(p.id)?'diagram-neutral':'diagram-player';return `<circle class="${cls}" cx="${p.x}" cy="${p.y}" r="3"/><text class="diagram-player-label" x="${p.x}" y="${p.y+.9}">${p.role==='keeper'?'K':''}</text>`}).join('');svg+=d.labels.map(l=>`<text class="diagram-label" x="${l.x}" y="${l.y}">${esc(l.text)}</text>`).join('');return svg+'</svg>'}
function exerciseMatchesPriority(exercise,priority){return exercise.feedbackPriorities.includes(priority)}
function populateExercisePriorities(){let category=$('#exerciseCategory'),priority=$('#exercisePriority'),priorities=category.value?priorityCategory(category.value).priorities:[];priority.innerHTML=priorities.length?`<option value="">Kies een concrete leerprioriteit</option>`+priorities.map(value=>`<option value="${esc(value)}">${esc(value)}</option>`).join(''):'<option value="">Kies eerst een hoofdcategorie</option>';priority.disabled=!priorities.length}
function feedbackPriorityChecklist(){return PRIORITY_TAXONOMY.map(category=>`<div class="priority-category"><p class="label">${esc(category.label)}</p>${category.priorities.map(priority=>`<label><input type="checkbox" value="${esc(priority)}">${esc(priority)}</label>`).join('')}</div>`).join('')}
function renderLibrary(){let el=$('#exerciseLibrary');if(!el)return;let priority=$('#exercisePriority')?.value||'',exercises=priority?EXERCISES.filter(exercise=>exerciseMatchesPriority(exercise,priority)):EXERCISES,status=$('#exerciseSelectionStatus');if(status)status.textContent=priority?(exercises.length?`${exercises.length} passende oefening${exercises.length===1?'':'en'} voor ${priority}.`:'Geen passende oefening in de huidige bibliotheek.'):'Toon alle oefeningen.';el.innerHTML=exercises.length?exercises.map(e=>{let idealStatus=getScalabilityStatus(e,e.idealPlayers);return `<article class="exercise-card"><div class="exercise-card-copy"><p class="tag">${esc(e.exerciseType)}</p><h3>${esc(e.title)}</h3><p class="scalability-badge">${esc(scalabilityLabel(e))}</p><p><strong>Doel:</strong> ${esc(e.primaryObjective)}</p><p><strong>Leeftijd:</strong> ${esc(e.ageGroups.join(', '))} · <strong>Spelers:</strong> ${e.diagram.players.length} · <strong>Duur:</strong> ${e.durationMin} min</p><p><strong>Materiaal:</strong> ${esc(e.materials.join(', '))}</p><p class="exercise-status">Kernbezetting: ${e.idealPlayers} · Basisstatus: ${idealStatus}</p><button class="secondary" type="button" data-open-exercise="${esc(e.id)}">Oefening openen</button></div>${renderDiagram(e)}</article>`}).join(''):'<p>Geen passende oefening in de huidige bibliotheek.</p>';$$('[data-open-exercise]').forEach(button=>button.onclick=()=>showExerciseDetail(button.dataset.openExercise))}
function listValues(values){return values?.length?`<ul>${values.map(value=>`<li>${esc(value)}</li>`).join('')}</ul>`:'<p>—</p>'}
function showExerciseDetail(exerciseId){let exercise=EXERCISES.find(item=>item.id===exerciseId);if(!exercise)return;let status=getScalabilityStatus(exercise,exercise.idealPlayers);$('#exerciseDetail').innerHTML=`<button class="secondary dossier-back" type="button" data-back-to-exercises>← Terug naar oefeningen</button><div class="section-heading compact"><p class="eyebrow">OEFENINGSDOSSIER</p><h2>${esc(exercise.title)}</h2><p>${esc(exercise.exerciseType)} · ${esc(exercise.ageGroups.join(', '))}</p></div><div class="exercise-detail-grid"><div><p><strong>Primair leerdoel:</strong> ${esc(exercise.primaryObjective)}</p><h3>Secundaire leerdoelen</h3>${listValues(exercise.secondaryObjectives)}<h3>Organisatie</h3><p><strong>Veld:</strong> ${esc(exercise.fieldSize)} · <strong>Duur:</strong> ${exercise.durationMin} min</p><p><strong>Spelers:</strong> ${exercise.minPlayers}–${exercise.maxPlayers} · kernbezetting ${exercise.idealPlayers}</p><p>${esc(exercise.organization)}</p><p><strong>Rotatie/wissels:</strong> ${exercise.rotationPossible||exercise.substitutePossible?'Mogelijk':'Niet voorzien'}${exercise.parallelGroupPossible?' · Deelgroepen/parallel mogelijk':''}</p><h3>Materiaal</h3>${listValues(exercise.materials)}<h3>Coaching</h3>${listValues(exercise.coachingPoints)}<h3>KVC-principes</h3>${listValues(exercise.kvcPrinciples)}<h3>Wedstrijdoverdracht</h3><p>${esc(exercise.matchTransfer)}</p><h3>Progressies</h3><p><strong>A:</strong> ${esc(exercise.progressionA||'—')}</p><p><strong>B:</strong> ${esc(exercise.progressionB||'—')}</p><p><strong>Vereenvoudiging:</strong> ${esc(exercise.regression||'—')}</p><h3>Schaalbaarheid</h3><p><strong>Status:</strong> ${esc(status)} · <strong>Fysieke belasting:</strong> ${esc(exercise.physicalLoad)}</p><p>${esc(exercise.organizationNotes)}</p><h3>Bron/referentie</h3><p>${esc(exercise.source)} · ${esc(exercise.sourceType)}</p></div><div>${renderDiagram(exercise)}</div></div>`;$('#exerciseOverview').classList.add('hidden');$('#exerciseDetail').classList.remove('hidden');$('[data-back-to-exercises]').onclick=showExerciseOverview}
function showExerciseOverview(){$('#exerciseDetail').classList.add('hidden');$('#exerciseDetail').innerHTML='';$('#exerciseOverview').classList.remove('hidden')}
async function refresh(){
	let ts=(await all('trainings')).sort((a,b)=>b.date.localeCompare(a.date));
	let fs=await all('feedback');
	renderLibrary();
	const feedbackFor=t=>fs.filter(f=>f.trainingId===t.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
	const primaryFor=q=>q.find(f=>f.primary)?.primary||'Geen hoofdfocus gekozen';
	// Bepaal huidige hoofdfocus: meest recent expliciet gekozen `primary`
	let recentWithPrimary = fs.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).find(f=>f.primary);
	if(recentWithPrimary){
		$('#priorityTitle').textContent = recentWithPrimary.primary;
		let training = ts.find(t=>t.id===recentWithPrimary.trainingId);
		let trainingLabel = training? `${esc(training.title)} · ${date(training.date)}` : 'Onbekende training';
		$('#priorityText').textContent = `Gekozen door trainer op ${createdDate(recentWithPrimary.createdAt)} bij ${trainingLabel}. Secundaire observaties — Goed: ${esc(recentWithPrimary.good.join(', ')||'—')} · Moeilijk: ${esc(recentWithPrimary.difficult.join(', ')||'—')} · Terug: ${esc(recentWithPrimary.repeat.join(', ')||'—')}`;
	}else{
		$('#priorityTitle').textContent = 'Geen hoofdfocus gekozen';
		$('#priorityText').textContent = 'Er is geen recente expliciete hoofdfocus gekozen.';
	}

	$('#trainingList').innerHTML = ts.length?ts.map(t=>{let q=feedbackFor(t);return `<article class="training-item"><span class="tag">Concept</span><h3>${esc(t.title)}</h3><p>${date(t.date)} · ${esc(t.priority)}</p><p>${t.attendees==null?'Aanwezigheid niet geregistreerd':`${t.attendees} aanwezige speler(s)`} · ${q.length} feedback-item(s)</p><p><strong>Hoofdfocus:</strong> ${esc(primaryFor(q))}</p><div class="training-actions"><button class="secondary" type="button" data-open-training="${esc(t.id)}">Openen</button><button class="danger" type="button" data-delete-training="${esc(t.id)}">Verwijderen</button></div></article>`}).join(''):'<p>Nog geen training bewaard.</p>';
	$$('[data-open-training]').forEach(x=>x.onclick=()=>showDossier(x.dataset.openTraining));
	$$('[data-delete-training]').forEach(x=>x.onclick=()=>deleteTraining(x.dataset.deleteTraining));

	let form=$('#feedbackForm'),gate=$('#feedbackGate'),sel=$('#feedbackTraining');
	if(!ts.length){
		gate.textContent='Maak en bewaar eerst een training. Daarna kun je er feedback aan koppelen.';form.classList.add('hidden')
	}else{
		gate.textContent='Kies hieronder de training waarover je feedback geeft.';form.classList.remove('hidden');let old=sel.value;sel.innerHTML=ts.map(t=>`<option value="${t.id}">${date(t.date)} — ${esc(t.title)}</option>`).join('');if(ts.some(t=>t.id===old))sel.value=old
	}

	// Historiek: markeer feedbacks met een expliciete hoofdfocus
	$('#historyList').innerHTML = ts.length?ts.map(t=>{let q=fs.filter(f=>f.trainingId===t.id);return `<article class="training-item"><h3>${esc(t.title)}</h3><p>${date(t.date)} · ${esc(t.priority)}</p>${q.length?`<p><strong>${q.length} feedback-item(s)</strong></p>`+q.map(f=>{let primaryHtml = f.primary?`<p><strong>Hoofdfocus gekozen: ${esc(f.primary)}</strong></p>`:'';return `${primaryHtml}<p>✓ Goed: ${esc(f.good.join(', ')||'—')}<br>! Moeilijk: ${esc(f.difficult.join(', ')||'—')}<br>↺ Terug: ${esc(f.repeat.join(', ')||'—')}</p>`}).join(''):'<p>Nog geen feedback bij deze training.</p>'}</article>`}).join(''):'<p>Nog geen trainingsdossiers.</p>'}
async function showDossier(trainingId){
	let t=await one('trainings',trainingId);if(!t)return;
	let q=(await all('feedback')).filter(f=>f.trainingId===trainingId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
	$('#trainingDossier').innerHTML=`<button class="secondary dossier-back" type="button" data-back-to-training>← Terug naar trainingen</button><div class="section-heading compact"><p class="eyebrow">TRAININGSDOSSIER</p><h3>${esc(t.title)}</h3><p>${date(t.date)} · ${esc(t.priority)}</p></div><p><strong>Aanwezige spelers:</strong> ${t.attendees==null?'Niet geregistreerd':t.attendees}</p><p><strong>Notitie:</strong> ${esc(t.notes||'—')}</p><h4>Gekoppelde feedback (${q.length})</h4>${q.length?q.map(f=>`<div class="feedback-entry"><p><strong>Wat ging goed:</strong> ${esc(f.good.join(', ')||'—')}</p><p><strong>Wat ging moeilijk:</strong> ${esc(f.difficult.join(', ')||'—')}</p><p><strong>Wat moet terugkomen:</strong> ${esc(f.repeat.join(', ')||'—')}</p><p><strong>Hoofdfocus:</strong> ${esc(f.primary||'Geen hoofdfocus gekozen')}</p></div>`).join(''):'<p>Nog geen feedback bij deze training.</p>'}`;
	$('#trainingOverview').classList.add('hidden');
	$('#trainingDossier').classList.remove('hidden');
	$('[data-back-to-training]').onclick=showTrainingOverview;
}
function showTrainingOverview(){
	$('#trainingDossier').classList.add('hidden');
	$('#trainingOverview').classList.remove('hidden');
}
async function deleteTraining(trainingId){
	let t=await one('trainings',trainingId);if(!t)return;
	if(!window.confirm(`Training "${t.title}" en alle gekoppelde feedback verwijderen?`))return;
	let tx=db.transaction(['trainings','feedback'],'readwrite'),feedbackStore=tx.objectStore('feedback'),trainingStore=tx.objectStore('trainings');
	let linked=await req(feedbackStore.index('trainingId').getAll(trainingId));
	linked.forEach(f=>feedbackStore.delete(f.id));trainingStore.delete(trainingId);
	await new Promise((ok,no)=>{tx.oncomplete=ok;tx.onerror=()=>no(tx.error);tx.onabort=()=>no(tx.error||Error('Verwijderen afgebroken.'))});
	$('#trainingDossier').classList.add('hidden');showTrainingOverview();status(true,'Opslag in orde');await refresh();
}
function view(x){if(x==='training')showTrainingOverview();$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===x));$$('.view').forEach(v=>v.classList.toggle('active',v.id===x));refresh()}
async function init(){
	$('#trainingPriority').innerHTML=priorityOptionGroups();
	let exerciseCategory=$('#exerciseCategory'),exercisePriority=$('#exercisePriority');exerciseCategory.innerHTML=`<option value="">Kies een hoofdcategorie</option>`+PRIORITY_TAXONOMY.map(category=>`<option value="${esc(category.id)}">${esc(category.label)}</option>`).join('');populateExercisePriorities();exerciseCategory.onchange=()=>{populateExercisePriorities();renderLibrary()};exercisePriority.onchange=renderLibrary;
	// populate checkbox lists
	['good','difficult','repeat'].forEach(g=>{$(`[data-group="${g}"]`).innerHTML=feedbackPriorityChecklist()});
	// ensure feedback primary selector exists (inject if not present) and populate its options
	let primaryOptions = `<option value="">Geen hoofdfocus</option>` + priorityOptionGroups();
	if($('#feedbackPrimary')){
		$('#feedbackPrimary').innerHTML = primaryOptions;
	}else{
		let liveEl = $('#livePriority');
		if(liveEl) liveEl.parentElement.insertAdjacentHTML('beforebegin', `<label>Hoofdfocus voor de volgende training<select id="feedbackPrimary" name="primary">${primaryOptions}</select></label>`);
	}

	$('#trainingForm [name=date]').value=new Date().toISOString().slice(0,10);
	try{if(!window.indexedDB)throw Error();db=await open();await put('trainings',{id:'healthcheck',date:'2099-01-01',title:'__healthcheck__',priority:P[0]});let tx=db.transaction('trainings','readwrite');tx.objectStore('trainings').delete('healthcheck');status(true,'Opslag in orde');await refresh()}catch(e){console.error(e);status(false,'Opslag niet beschikbaar');$$('form button,input,select').forEach(x=>x.disabled=true)}$$('.nav').forEach(x=>x.onclick=()=>view(x.dataset.view));$$('[data-go]').forEach(x=>x.onclick=()=>view(x.dataset.go));
$('#trainingForm').onsubmit=async e=>{e.preventDefault();let s=$('#trainingStatus'),f=new FormData(e.target);try{s.textContent='Bewaren…';await put('trainings',{id:id(),type:'training',date:f.get('date'),title:f.get('title').trim(),priority:f.get('priority'),attendees:Number(f.get('attendees')),notes:f.get('notes').trim(),createdAt:new Date().toISOString()});s.textContent='✓ Training bewaard en gecontroleerd.';e.target.reset();$('#trainingForm [name=date]').value=new Date().toISOString().slice(0,10);await refresh()}catch(x){s.textContent='⚠ Training kon niet bevestigd worden.';s.className='form-status error'}};
$('#feedbackForm').onsubmit=async e=>{e.preventDefault();let s=$('#feedbackStatus'),trainingId=$('#feedbackTraining').value;try{if(!await one('trainings',trainingId))throw Error('De gekozen training bestaat niet.');let primary = $('#feedbackPrimary')?$('#feedbackPrimary').value:null; if(primary==='') primary=null;let f={id:id(),type:'feedback',parentType:'training',parentId:trainingId,trainingId,good:picked('good'),difficult:picked('difficult'),repeat:picked('repeat'),primary:primary,createdAt:new Date().toISOString()};if(!f.good.length&&!f.difficult.length&&!f.repeat.length)throw Error('Kies minstens één feedbackpunt.');s.textContent='Bewaren…';await put('feedback',f);if(!await one('feedback',f.id))throw Error('Feedback niet teruggevonden.');s.textContent='✓ Feedback opgeslagen bij de gekozen training en gecontroleerd.';$$('#feedbackForm input').forEach(x=>x.checked=false);if($('#feedbackPrimary'))$('#feedbackPrimary').value='';await live();await refresh()}catch(x){s.textContent='⚠ '+x.message;s.className='form-status error'}};$('#feedbackForm').onchange=live}
async function live(){
	let sel = $('#feedbackPrimary')?$('#feedbackPrimary').value:'';
	if(sel && sel!=='') $('#livePriority').textContent = esc(sel);
	else $('#livePriority').textContent = 'Geen hoofdfocus gekozen.';
}
init();
})();
